name: Deploy to PowerShell Gallery

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2
    - name: Update version number
      run: |
        Set-Location -Path D:\a\PdfTools\PdfTools
        [Version]$CurrentVersion = (Import-PowerShellDataFile PsPdf\PsPdf.psd1).ModuleVersion
        $NewVersion = "$($CurrentVersion.Major).$($CurrentVersion.Minor + 1)"
        New-Item PsPdf\PsPdf.dll ## This shouldn't be necessary but PS7 fails to read the manifest without a file with this name present. It doesn't matter that it's empty
        Update-ModuleManifest -Path PsPdf\PsPdf.psd1 -ModuleVersion $NewVersion
    - name: Check in new version number
      uses: EndBug/add-and-commit@v8.0.2
      with:
        # Arguments for the git add command
        add: PsPdf\PsPdf.psd1
        # The name of the user that will be displayed as the author of the commit
        author_name: DeployBot
        message: CI Skip
        # The token used to make requests to the GitHub API. It's NOT used to make commits and should not be changed.
        github_token: ${{ github.token }}
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Install platyPS
      run: Install-Module platyPS -Force
    - name: Restore Packages
      run: nuget restore PdfTools.sln
    - name: Build Solution
      run: msbuild.exe .\PdfTools.sln /p:platform="Any CPU" /p:configuration="Release"
    - name: Test
      run: dotnet test --verbosity normal
    - name: Publish to PowerShell Gallery
      run: |
        Publish-Module -Name "D:\a\PdfTools\PdfTools\PsPdf\bin\Release\PsPdf.psd1" -NugetApiKey $ {{API_KEY }}
