name: Deploy to PowerShell Gallery

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update version number
      run: |
        [Version]$CurrentVersion = (Import-PowerShellDataFile .\PsPdf.psd1).ModuleVersion
        $NewVersion = "$($CurrentVersion.Major).$($CurrentVersion.Minor + 1)"
        Update-ModuleManifest -Path .\PsPdf.psd1 -ModuleVersion $NewVersion
    - name: Check in new version number
      uses: EndBug/add-and-commit@v8.0.2
      with:
        # Arguments for the git add command
        add: PsPdf.psd1
        # The name of the user that will be displayed as the author of the commit
        author_name: DeployBot
        message: CI Skip
        # The token used to make requests to the GitHub API. It's NOT used to make commits and should not be changed.
        github_token: ${{ github.token }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
