name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: True

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Super-Linter
      uses: github/super-linter@v4.8.7
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Install platyPS
      run: Install-Module platyPS -Force
    - name: Restore Packages
      run: nuget restore PdfTools.sln
    - name: Build Solution
      run: msbuild.exe .\PdfTools.sln /p:platform="Any CPU" /p:configuration="Release"
    - name: Test
      run: dotnet test --no-build --verbosity normal
