name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: True

jobs:
  run-lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Install platyPS
      run: Install-Module platyPS -Force
    - name: Restore Packages
      run: nuget restore PdfTools.sln
    - name: Build Solution
      run: msbuild.exe .\PdfTools.sln /p:platform="Any CPU" /p:configuration="Release"
    - name: Test
      run: dotnet test --verbosity normal --no-build --configuration Release
